### ISSUE TITLE
[signal SIGBUS: bus error code=0x2 addr=0x1e4001 pc=0x2535]

### ISSUE THREAD

**Issue by AllenRay** [edsrzf/mmap-go#12]
go version 
 1.7.1 
os
macos sierra

when i use mmap-go to write bytes to file occur error.  the stack as below

 unexpected fault address 0x1e4001
  fatal error: fault
  [signal SIGBUS: bus error code=0x2 addr=0x1e4001 pc=0x2535]
  
  goroutine 1 [running]:
  runtime.throw(0xb37ee, 0x5)
    /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420035da0 sp=0xc420035d80
  runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:21 +0x1d0 fp=0xc420035df8 sp=0xc420035da0
  main.main()
    /Users/leizhenyu/work/src/github.com/GoRocketMQ/start/main-1.go:58 +0x4f5 fp=0xc420035f48 sp=0xc420035df8
  runtime.main()
    /usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420035fa0 sp=0xc420035f48
  runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420035fa8 sp=0xc420035fa0
  exit status 2

the line 58 code as below

mmaped[0] = 'x'

**Comment by dinhvankiet124** [comment]
me too :(

**Comment by jcmiao** [comment]
the same problem

**Comment by edsrzf** [comment]
A minimal reproduction case would be helpful here.

**Comment by dspasibenko** [comment]
@edsrzf I hit the same problem on macos. This reproduced when provided mapped size is bigger than actual file size. So, in my case the code, called for an empty f: 
```
mf, err := mmap.MapRegion(f, 12345, mmap.RDWR, 0, 0)
...
```
doesn't change the file f size, so it remained 0. Seems like macos doesn't extend the file with the mapping. Can be easily fixed by `f.Truncate(12345)` for the example above. Please consider.
